apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: ws
      protocol: TCP
      targetPort: 4000
      port: 4000
    - name: nodejs
      protocol: TCP
      targetPort: 4001
      port: 4001
  type: ClusterIP
